### ISSUE TITLE
Use Async WebDiver in Tests

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#591]
### Current Situation

Currently, we run tests which rely on the browser using a synchronously executing web driver from Selenium. As a result, server implementations have been required to provide a `run_in_thread` method such that they can be run in the background while the blocking test code is allowed to proceed.

Unfortunately, some async servers don't play well with threads. This is primarily due to the fact that cleanly stopping a thread can be somewhat challenging. For example, IDOM is currently locked into version `sanic<19.12` because later releases have been developed without consideration for threading.

### Proposed Actions

As a result, we should switch to an async web driver like [arsenic](https://github.com/HDE/arsenic) or [pyppeteer](https://miyakogi.github.io/pyppeteer/reference.html) and add a `ServerType.run_async` method to the various server implementations. Once this is done we can deprecate the `ServerType.run_in_thread` method.

Then lastly, we can upgrade Sanic to the latest version.

### Work Items

- [ ] Implement `ServerType.run_async` and switch to async web driver
- [ ] Mark `ServerType.run_in_thread` as deprecated
- [ ] Update downstream libraries (e.g. custom component template and anything made from it).
- [ ] Upgrade `sanic` and raise when `run_in_thread` is called for `sanic>=19.12`
- [ ] Remove `ServerType.run_in_thread`

**Comment by Archmonger** [comment]
We can also use [arsenic](https://github.com/HDE/arsenic) instead of Selenium.

It would save us a lot of effort in developing custom tooling.

**Comment by rmorshea** [comment]
This is somewhat more urgent as a result of: https://github.com/idom-team/idom/security/dependabot/9

**Comment by Archmonger** [comment]
Security issues are not publicly visible, and I don't have access to them.

**Comment by rmorshea** [comment]
I edited the link
