### ISSUE TITLE
Create "Managing State" Document

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#596]
### Current Situation

The docs are still unfinished. The next major set of sections to complete is "Managing State"

### Proposed Actions

Write the "Managing State" documentation as per the React docs: https://beta.reactjs.org/learn/managing-state

### Work Items

Write the following sections.

- [ ] Managing State
  - [ ] Reacting to Input with State
  - [ ] Choosing the State Structure
  - [ ] Sharing State Between Components
  - [ ] Preserving and Resetting State
  - [ ] Extracting State Logic into a Reducer
  - [ ] Passing Data Deeply with Context
  - [ ] Scaling Up with Reducer and Context

**Comment by Archmonger** [comment]
Closing this in favor of the docs rewrite #863
