### ISSUE TITLE
Rename Install Target idom[stable] to idom[any]

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#600]
### Current Situation

The `idom[stable]` install target makes it seem like this is a "stable" release of IDOM rather than a "stable" server implementation. At the moment though, our tests are good enough to guarantee that all supplied server implementations work correctly.

### Proposed Actions

We should rename the install target to `idom[any]` in order to better imply that you don't care what implementation you're using.

### Work Items

- [ ] rename install target to `idom[any]` and update docs
- [ ] make `idom[stable]` an alias for `[any]`
- [ ] add issue to remove `idom[stable]` install target after `1.0`

**Comment by rmorshea** [comment]
The idea of a "default" install target has been removed.
